InTouchLearn/InTouchLearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("classrooms/", include("classrooms.urls", namespace="classrooms")),
    path("social/", include("socialmedia.urls", namespace="socialmedia")),
]

InTouchLearn/main/urls.py
from django.urls import path
from main import views
from socialmedia import views as social_views


urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.login, name="login"),
    path("accounts/register/", views.register, name="register"),
    path("accounts/logout/", views.logout, name="logout"),
    path("confirm_email/<uidb64>/<token>", views.confirm_email, name="confirm_email"),

]

InTouchLearn/socialmedia/urls.py
from django.urls import path
from .views import (
    post_list_view, post_detail_view, post_edit_view, post_delete_view,
    add_like, add_dislike, add_comment_like, add_comment_dislike,
    comment_reply_view, editprofile, profile, picture_upload, add_comment, get_comments, search, landing
)
from .chat import chat, create_conversation, send_message, get_messages

app_name = 'socialmedia'
urlpatterns = [
    path('landing/', landing, name='landing'),
    path('', post_list_view, name='post-list'),
    path('post/<int:pk>/', post_detail_view, name='post-detail'),
    path('post/edit/<int:pk>/', post_edit_view, name='post-edit'),
    path('post/delete/<int:pk>/', post_delete_view, name='post-delete'),
    path('post/<int:pk>/like', add_like, name='like'),
    path('post/<int:pk>/dislike', add_dislike, name='dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/like', add_comment_like, name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', add_comment_dislike, name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply', comment_reply_view, name='comment-reply'),
    path('post/<int:post_pk>/comments/', get_comments, name='get_comments'),
    path('editProfile', editprofile, name='editprofile'),
    path('profile/<str:username>/', profile, name='profile'),
    path('picture_upload', picture_upload, name='picture_upload'),
    path('chat/', chat, name='chat'),
    path('create_conversation/', create_conversation, name='create_conversation'),
    path('send_message/', send_message, name='send_message'),
    path('get_messages/', get_messages, name='get_messages'),
    path('search/', search, name='search'),


]

InTouchLearn/socialmedia/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone



class Post(models.Model):
    body = models.TextField()
    image = models.ImageField(upload_to='uploads/post_photos', blank=True, null=True)
    video = models.FileField(upload_to='uploads/post_videos', blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='dislikes')


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='comment_likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL , blank=True, related_name='comment_dislikes')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_on').all()
    @property
    def is_parent(self):
     if self.parent is None:
        return True
    
     return False  
    

class conversation(models.Model):
    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user2')
    created_on = models.DateTimeField(default=timezone.now)
    @property
    def messages(self):
        return message.objects.filter(conversation=self).order_by('created_on').all()
    
class message(models.Model):
    conversation = models.ForeignKey('conversation', on_delete=models.CASCADE)
    message = models.TextField()
    image = models.ImageField(upload_to='uploads/message_photos', blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)
    @property
    def is_sender(self):
        if self.author == self.conversation.user1:
            return True
        return False

InTouchLearn/socialmedia/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))
    image = forms.ImageField(required=False)
    video = forms.FileField(required=False)
   
    class Meta:
        model = Post
        fields = ['body', 'image', 'video']

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    class Meta:
        model = Comment
        fields = ['comment']

InTouchLearn/socialmedia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from .models import Post, Comment

from django.contrib.auth import get_user_model

from main.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from django.http import JsonResponse, HttpResponseBadRequest

from django.shortcuts import redirect

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

@login_required
def editprofile(request):
    if request.method == 'POST':
        # Récupérer l'utilisateur actuellement connecté
        user = request.user
        
        # Récupérer les données envoyées dans le formulaire
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        bio = request.POST.get('bio')
        profile_picture = request.FILES.get('profile_picture')
        resume = request.FILES.get('resume')

        if username:
            user.username = username
        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name
        if bio:
            user.bio = bio
        if profile_picture:
            user.profile_picture = profile_picture
        if resume:
            user.resume = resume

        user.save()
        return redirect('socialmedia:profile', username=user.username)
    else:
        return render(request, 'socialmedia/editprofile.html')
        
def landing(request):
    students_counts = User.objects.filter(role='student').count()
    teachers_counts = User.objects.filter(role='teacher').count()
    posts_counts = Post.objects.all().count()

    context = {
        'students_counts': students_counts,
        'teachers_counts': teachers_counts,
        'posts_counts': posts_counts,
    }
    return render(request, 'socialmedia/landing.html', context)



def profile(request, username):
    target_user = get_object_or_404(User, username=username)
    userInformation = {
        "username": target_user.username,
        "email": target_user.email,
        "role": target_user.role,
        "first_name": target_user.first_name,
        "last_name": target_user.last_name,
        "bio": target_user.bio,
        "profile_picture": target_user.profile_picture
    }

    posts = Post.objects.filter(author=target_user).order_by('-created_on')

    context = {
        'curr_profile': userInformation,
        'post_list': posts,
    }
    return render(request, 'socialmedia/profile.html', context)

@login_required
def post_list_view(request):
    posts = Post.objects.all().order_by('-created_on')
    paginator = Paginator(posts, 15)  # Set the number of posts per page

    page_number = request.GET.get('page', 1)  # Get the current page number, default to 1

    try:
        page_obj = paginator.page(page_number)
    except:
        pass
    # except PageNotAnInteger:
    #     page_obj = paginator.page(1)
    # except EmptyPage:
    #     page_obj = paginator.page(paginator.num_pages)

    pages = {
        'page_obj': page_obj,
        'page_number': page_number,
        'num_pages': paginator.num_pages,  # Add the total number of pages
    }


    if request.method == 'POST':
        text = request.POST.get('body')
        
        print("===>>", text)
        if text:
            new_post = Post(body=text, author=request.user)
            if request.FILES.get('media'):
                file = request.FILES.get('media')
                print("===>>", file.content_type)
                #check if the file is an image
                if file.content_type.startswith('image'):
                    new_post.image = file
                #check if the file is a video
                elif file.content_type.startswith('video'):
                    new_post.video = file
        try:
            new_post.save()
            print("===>>", "Post Saved")
            
        except Exception as e:
            print(e)
            print("===>>", "Post Not Saved")
    try:
        user = User.objects.get(id=request.session["user_id"])
    except:
        return redirect('logout')
    userInformation = {
        "username": user.username,
        "email": user.email,
        "role": user.role,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "bio": user.bio,
        "profile_picture": user.profile_picture
    }
    context = {
        'post_list': page_obj,
        'user': userInformation,
        'pages': pages,
        }
    return render(request, 'socialmedia/post_list.html', context)



@login_required
def post_detail_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

    comments = Comment.objects.filter(post=post).order_by('-created_on')

    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'socialmedia/post_detail.html', context)

@login_required
def post_edit_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        return redirect('post-detail', pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('socialmedia:post-detail', pk=pk)
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'socialmedia/post_edit.html', context)

@login_required
def post_delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        return redirect('post-list')

    if request.method == 'POST':
        post.delete()
        return redirect('socialmedia:post-list')

    context = {
        'post': post,
    }
    return render(request, 'socialmedia/post_delete.html', context)


@login_required
def add_like(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        is_like = request.user in post.likes.all()
        is_dislike = request.user in post.dislikes.all()

        if is_like:
            post.likes.remove(request.user)
            liked = False
        else:
            if is_dislike:
                post.dislikes.remove(request.user)
            post.likes.add(request.user)
            liked = True

        like_count = post.likes.all().count()
        dislike_count = post.dislikes.all().count()

        return JsonResponse({'like_count': like_count, 'dislike_count': dislike_count, 'liked': liked})
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

@login_required
def add_dislike(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        is_like = request.user in post.likes.all()
        is_dislike = request.user in post.dislikes.all()

        if is_dislike:
            post.dislikes.remove(request.user)
            disliked = False
        else:
            if is_like:
                post.likes.remove(request.user)
            post.dislikes.add(request.user)
            disliked = True

        like_count = post.likes.all().count()
        dislike_count = post.dislikes.all().count()

        return JsonResponse({'like_count': like_count, 'dislike_count': dislike_count, 'disliked': disliked})
    else:
        return HttpResponseBadRequest()


@login_required
def add_comment_like(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    is_dislike = False

    for dislike in comment.dislikes.all():
        if dislike == request.user:
            is_dislike = True
            break

    if is_dislike:
        comment.dislikes.remove(request.user)

    is_like = False

    for like in comment.likes.all():
        if like == request.user:
            is_like = True
            break

    if not is_like:
        comment.likes.add(request.user)

    if is_like:
        comment.likes.remove(request.user)

    next_url = request.POST.get('next', '/')
    return redirect(next_url)


@login_required
def add_comment_dislike(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    is_like = False

    for like in comment.likes.all():
        if like == request.user:
            is_like = True
            break

    if is_like:
        comment.likes.remove(request.user)

    is_dislike = False

    for dislike in comment.dislikes.all():
        if dislike == request.user:
            is_dislike = True
            break

    if not is_dislike:
        comment.dislikes.add(request.user)

    if is_dislike:
        comment.dislikes.remove(request.user)

    next_url = request.POST.get('next', '/')
    return redirect(next_url)

@login_required
def comment_reply_view(request, post_pk, pk):
    post = get_object_or_404(Post, pk=post_pk)
    parent_comment = get_object_or_404(Comment, pk=pk)
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()
            return redirect('post-detail', pk=post_pk)

    context = {
        'form': form,
        'post': post,
        'parent_comment': parent_comment,
    }

InTouchLearn/socialmedia/templates/socialmedia/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'socialmedia/images/logo.svg' %}">
    <title>Academy Link</title>
    <!-- .................CUSTOM CSS LINK................. -->
    <link rel="stylesheet" href="{% static 'socialmedia/css/Style.css' %}">

    <!-- ...............Font Awesome Link................. -->
    <link rel="stylesheet" href="{% static 'socialmedia/css/fontawesome-free-6.3.0-web/css/all.css' %}">

    <!-- ...............Swiper Slider Link.................. -->
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    <!-- ...................Start Navbar................... -->
    <nav>
        <div class="container nav-container">
            <div class="logo">
                <img src="{% static 'socialmedia/images/logo.svg' %}" alt="">
                <div class="row">
                    <span>Academy</span>
                    <small>Link</small>
                </div>
            </div>
            <div class="serch-bar">
                <form action="{% url 'socialmedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input name="search" type="search" placeholder="Search" id="search-input">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="add-post">
                <div class="creatPostPop">
                    <label for="add-post" class="btn btn-primary mini-button ">Add Post</label>
                </div>
                <div class="profile-picture" id="my-profile-picture">
                    <img src="{{ user.profile_picture.url }}" alt="">
                </div>
            </div>
        </div>
    </nav>
    <!-- ...................Start Navbar................... -->

    <!-- ...................Start Main Section................... -->
    <main>
        <div class="container main-container">
            <!--================== Main Left Start ================== -->
            <div class="main-left">
                <!-- .......Profile.Start........ -->
                <a class="profile">
                    <div class="profile-picture" id="my-profile-picture">
                        <img src="{{ user.profile_picture.url }}" alt="profile">
                    </div>
                    <div class="profile-handle">
                        <h4>{{ user.username}}</h4>
                        <p class="text-gry">
                            {{ user.role }}
                        </p>
                    </div>
                </a>
                <!-- .......Profile.End........ -->

                <!-- .........Start Aside Bar.......... -->
                <aside>
                    <a class="menu-item active">
                        <span><img src="{% static 'socialmedia/images/svg/house-door.svg'%}" alt=""></span>
                        <h3>Home</h3>
                    </a>
                    <a class="menu-item" href="{% url 'socialmedia:chat' %}">
                        <span><img src="{% static 'socialmedia/images/svg/chat-left-dots.svg'%}" alt=""></span>
                        <small class="notfy-counter" id="notfyCoutner2">3</small>
                        <h3>Message</h3>
                    </a>
                    {% if user.role != 'entreprise' %}
                    <a class="menu-item" href="/classrooms">
                        <span><img src="{% static 'socialmedia/images/svg/bookmarks.svg'%}" alt=""></span>
                        <h3>Classroom</h3>
                    </a>
                    {% endif %}
                    <a class="menu-item" id="theme">
                        <span><img src="{% static 'socialmedia/images/svg/palette.svg'%}" alt=""></span>
                        <h3>Theme</h3>
                    </a>

                    <!-- ...........Add Post Btn......... -->
                    <div class="creatPostPop">
                        <label for="add-post" class="btn btn-primary btn-lg creatPostPop" >Create A Post</label>
                    </div>
                </aside>
                <!-- ..........End Aside Bar........... -->
            </div>
            <!--==================  Main Left End =================== -->

            <!--================== Main Middle Start================== -->
            <div class="main-middle">
                <div class="middle-container">
                    <!--.............. Feed Aria Start............... -->
                    <div class="feeds">
                        {% block feeds %}
                        {% endblock %}
                    </div>
                    <!--.............. Feed Aria End............... -->
                </div>
            </div>
            <!--================== Main Middle End==================  -->
        </div>
    </main>
    <!-- ...................Start Main Section................... -->

    <!-- ...................Start PopUps Aria................... -->

    <!-- ................Start Profile-Popup............ -->
    <div class="popup profile-popup">
        <div>
            <div class="popup-box profile-popup-box">
                <h1>{{ user.username }}</h1>
                <p>{{ user.email }}</p>
                <div id="my-profile-picture">
                    <img src="{{ user.profile_picture.url }}">
                </div>
                <label for="profile-upload" class="btn btn-primary btn-lg">Update Profile Picture</label>
                <input type="file" accept="image/jpg, image/png, image/jpeg" id="profile-upload" data-csrf="{{csrf_token}}">
                <a href="{% url 'socialmedia:profile' user.username %}" class="btn btn-primary btn-lg" id="editProfile">Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-primary btn-lg" id="logoutbtn">Log Out</a>
            </div>
            <span class="close"><i class="fa fa-close"></i></span>
        </div>
    </div>
    <!-- ................End Profile-Popup............ -->

    <!-- ................Start Add Post Popup............ -->
    <div class="popup add-post-popup">
        <div>
            <form class="popup-box add-post-pop" action="{% url 'socialmedia:post-list' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Add New Post</h1>
                <div class="row post-title">
                    <input name="body" type="text" placeholder="What's on your mind ?" id="title-input">
                </div>
                <div class="row post-img">
                    <img src="" id="postIMg">
                    <label for="feed-pic-upload" class="feed-upload-button">
                        <span><i class="fa fa-add"></i></span>
                        Upload A Picture Or Video
                    </label>
                    <input name="media" type="file" id="feed-pic-upload">
                    <input type="submit" class="btn btn-primary btn-lg bbb" value="Add Post">
                </div>
            </form>
            <span class="close"><i class="fa fa-close"></i></span>
        </div>
    </div>
    <!-- ................End  Add Post Popup............ -->

    <!-- ................Start Theme Customize Popup............ -->
    <div class="popup theme-customize">
        <div>
            <div class="popup-box theme-customize-popup-box">
                <h1>Coustomize Your Theme</h1>
                <p>Manege Your Font Size, Color, and Background</p>

                <!-- ........Font Size....... -->
                <div class="font-size">
                    <h4>Font Size</h4>
                    <div>
                        <div>
                            <h6>Aa</h6>
                        </div>
                        <div class="choose-size">
                            <span class="font-size-1"></span>
                            <span class="font-size-2 "></span>
                            <span class="font-size-3 active"></span>
                            <span class="font-size-4"></span>
                            <span class="font-size-5"></span>
                        </div>
                        <div>
                            <h3>Aa</h3>
                        </div>
                    </div>
                </div>

                <!-- ..........Primary Colors........ -->
                <div class="colors">
                    <h4>Color</h4>
                    <div class="choose-color">
                        <span class="color-1 active"></span>
                        <span class="color-2 "></span>
                        <span class="color-3 "></span>
                        <span class="color-4 "></span>
                        <span class="color-5 "></span>
                    </div>
                </div>

                <!-- ...........Background Colors.......... -->
                <div class="background">
                    <h4>Background</h4>
                    <div class="choose-bg">
                        <div class="bg1 active">
                            <span></span>
                            <h5>Light</h5>
                        </div>
                        <div class="bg2">
                            <span></span>
                            <h5>Dark</h5>
                        </div>
                    </div>
                </div>
            </div>
            <span class="close"><i class="fa fa-close"></i></span>
        </div>
    </div>
    <!-- ................End  Theme Customize Popup............ -->

    <!-- ...................End PopUps Aria................... -->

    <!-- ...................Swiper JS Link.................. -->
    <script src="{% static 'socialmedia/css/Swiper/swiper-bundle.min.js' %}"></script>

    <!-- ...................Custom JS Link.................. -->
    <script>
        document.querySelector('.logo').addEventListener('click', () => {
            window.location.href = '/';
        });

    
    </script>
    <script src="{% static 'socialmedia/js/Script.js' %}"></script>
</body>
</html>

InTouchLearn/socialmedia/templates/socialmedia/post_detail.html
{% extends 'socialmedia/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block feeds %}
<!-- tailwind -->
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <div class="feed">
                <div class="feed-top">
                    <div class="user">
                        <div class="profile-picture">
                            <img src="{{ post.author.profile_picture.url }}" alt="">
                        </div>
                        <div class="info">
                            <h3>{{ post.author.username }}</h3>
                            <div class="time text-gry">
                                <small><span>{{ post.created_on|timesince }} ago</span></small>
                            </div>
                        </div>
                    </div>
                    {% if request.user == post.author %}
                    <span class="edit">
                        <a href="{% url 'socialmedia:post-edit' post.pk %}" style="color: #333;"><i class="far fa-edit"></i></a>
                        <a href="{% url 'socialmedia:post-delete' post.pk %}" style="color: #333;"><i class="fas fa-trash"></i></a>
                    </span>
                    {% endif %}
                </div>
                <div class="caption">
                    <div class="title">{{ post.body }}</div>
                </div>
                <div class="feed-img">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="{{ post.image.name }}">
                    {% endif %}
                </div>
                <div class="video-post">
                    {% if post.video %}
                        <div class="embed-responsive embed-responsive-16by9">
                            <video controls class="embed-responsive-item">
                                <source src="{{ post.video.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        </div>
                    {% endif %}
                </div>
                
                <div class="action-button">
                    <div class="interaction-button">
                        <button  data-post-id="{{ post.pk }}" class="btn btn-primary like-button">
                            {% if user in post.likes.all %}
                                <i class="fas fa-thumbs-up"> </i>
                            {% else %}
                                <i class="far fa-thumbs-up"> </i>
                            {% endif %}
                            <span id="like-count">{{ post.likes.all.count }}</span>
                        </button>
                        <button  data-post-id="{{ post.pk }}" class="btn btn-primary dislike-button">
                            {% if user in post.dislikes.all %}
                                <i class="fas fa-thumbs-down"> </i>
                            {% else %}
                                <i class="far fa-thumbs-down"> </i>
                            {% endif %}
                            <span id="dislike-count">{{ post.dislikes.all.count }}</span>
                        </button>
                    </div>
                </div>
                <div class="bookmark">
                    <i class="fa fa-bookmark"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="comments space-y-4">
        {% for comment in comments %}
          <div class="comment bg-white rounded-lg shadow-md p-4">
            <div class="user flex items-center">
              <div class="profile-picture mr-3">
                <img class="rounded-full w-10 h-10" src="{{ comment.author.profile_picture.url }}" alt="">
              </div>
              <div class="info">
                <h3 class="text-lg font-semibold">{{ comment.author.username }}</h3>
                <div class="time text-gray-500 text-sm">
                  <small><span>{{ comment.created_on|timesince }} ago</span></small>
                </div>
              </div>
            </div>
            <div class="caption mt-2">
              <div class="title text-gray-700">{{ comment.comment }}</div>
            </div>
          </div>
        {% endfor %}
      </div>
    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {% if field.label == 'Body' %}
                            {{ field|as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                        {% if field.help_text %}
                            <small class="text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <button class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}