InTouchLearn/InTouchLearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("classrooms/", include("classrooms.urls", namespace="classrooms")),
    path("social/", include("socialmedia.urls", namespace="socialmedia")),
]

InTouchLearn/classrooms/urls.py
from django.urls import path
from classrooms import views


app_name = "classrooms"
urlpatterns = [
    path("", views.home, name="home"),
    path("create_class_request/", views.create_class_request, name="create_class"),
    path("join_class_request/", views.join_class_request, name="join_class"),
    path('class/<int:id>',views.render_class,name='render_class'),
    path('create_assignment/<int:classroom_id>',views.create_assignment,name='create_assignment'),
    path('assignment_summary/<int:assignment_id>',views.assignment_summary,name='assignment_summary'),
    path('delete_assignment/<int:assignment_id>',views.delete_assignment,name='delete_assignment'),
    path('unenroll_class/<int:classroom_id>',views.unenroll_class,name='unenroll_class'),
    path('delete_class/<int:classroom_id>',views.delete_class,name='delete_class'),
    path('submit_assignment_request/<int:assignment_id>',views.submit_assignment_request,name='submit_assignment_request'),
    path('mark_submission_request/<int:submission_id>/<int:teacher_id>',views.mark_submission_request,name='mark_submission_request'),
    path('add_course/<int:classroom_id>',views.add_course,name='add_course'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('meeting/',views.videocall, name='meeting'),
    path('join/', views.join_room, name='join_room'),

]

InTouchLearn/main/urls.py
from django.urls import path
from main import views
from socialmedia import views as social_views


urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.login, name="login"),
    path("accounts/register/", views.register, name="register"),
    path("accounts/logout/", views.logout, name="logout"),
    path("confirm_email/<uidb64>/<token>", views.confirm_email, name="confirm_email"),

]

InTouchLearn/socialmedia/urls.py
from django.urls import path
from .views import (
    post_list_view, post_detail_view, post_edit_view, post_delete_view,
    add_like, add_dislike, add_comment_like, add_comment_dislike,
    comment_reply_view, editprofile, profile, picture_upload, add_comment, get_comments, search, landing
)
from .chat import chat, create_conversation, send_message, get_messages

app_name = 'socialmedia'
urlpatterns = [
    path('landing/', landing, name='landing'),
    path('', post_list_view, name='post-list'),
    path('post/<int:pk>/', post_detail_view, name='post-detail'),
    path('post/edit/<int:pk>/', post_edit_view, name='post-edit'),
    path('post/delete/<int:pk>/', post_delete_view, name='post-delete'),
    path('post/<int:pk>/like', add_like, name='like'),
    path('post/<int:pk>/dislike', add_dislike, name='dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/like', add_comment_like, name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', add_comment_dislike, name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply', comment_reply_view, name='comment-reply'),
    path('post/<int:post_pk>/comments/', get_comments, name='get_comments'),
    path('editProfile', editprofile, name='editprofile'),
    path('profile/<str:username>/', profile, name='profile'),
    path('picture_upload', picture_upload, name='picture_upload'),
    path('chat/', chat, name='chat'),
    path('create_conversation/', create_conversation, name='create_conversation'),
    path('send_message/', send_message, name='send_message'),
    path('get_messages/', get_messages, name='get_messages'),
    path('search/', search, name='search'),


]

InTouchLearn/classrooms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *
import datetime
from main.models import User as CustomUser

class CreateClassForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(CreateClassForm,self).__init__()
        self.fields['class_name'].label=''
        self.fields['section'].label=''
        self.fields['class_name'].widget.attrs['placeholder']='Class Name'
        self.fields['section'].widget.attrs['placeholder']='Section'
    
    class_name = forms.CharField(max_length=100,label='Class name')
    section = forms.CharField(max_length=100,label='Section')

class JoinClassForm(forms.Form):
    code = forms.CharField(max_length=10,label='code')

class CreateAssignmentForm(forms.Form):
    assignment_name = forms.CharField(max_length=50,label='Assignment Name')
    due_date = forms.DateField(initial=datetime.date.today(),label='Due Date')
    due_time = forms.TimeField(initial=datetime.time(10,10),label='Due Time')
    instructions = forms.CharField(label='Instructions',widget=forms.Textarea)
    total_marks = forms.IntegerField(label='Total Marks')

class SubmitAssignmentForm(forms.Form):
    submission_file = forms.FileField()

class UserRegisterationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['email'].label = ''
        self.fields['password1'].label = ''
        self.fields['password2'].label = ''
        self.fields['profile_picture'].label = ''
        self.fields['profile_picture'].widget.attrs['placeholder'] = 'Profile photo'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Re-enter Password'

    password1 = forms.CharField(label='Enter password', 
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', 
                                widget=forms.PasswordInput)
    
 
    class Meta:
        model = CustomUser
        fields = ("username","password1","password2",'email','profile_picture')
        help_texts = {
            "username":None,
        }

class UserAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['password'].label = ''
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'


    password = forms.CharField(label='Enter password', 
                                widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ("username","password")
        help_texts = {
            "username":None,
        }

InTouchLearn/classrooms/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import JsonResponse
import math, random 
from .models import Classrooms, Teachers, Students, Assignments, Submissions, CourseContent
from itertools import chain
from .forms import CreateAssignmentForm
from . import email
from datetime import datetime
from django.utils.timesince import timesince
from .decorators import student_required, teacher_required


@login_required
def home(request):
    # Get the teacher mapping for the current user
    teacher_mapping = Teachers.objects.filter(teacher_id=request.user).select_related('classroom_id')

    # Get the student mapping for the current user
    student_mapping = Students.objects.filter(student_id=request.user).select_related('classroom_id')

    # Combine the teacher and student mappings
    mappings = list(teacher_mapping) + list(student_mapping)

    # Get all teachers
    teachers_all = Teachers.objects.all()

    return render(request, 'classrooms/home.html', {
        'mappings': mappings,
        'teachers_all': teachers_all
    })

@login_required
def create_class_request(request):
    if request.POST.get('action') == 'post':
        classrooms = Classrooms.objects.all()
        existing_codes = []
        for classroom in classrooms:
            existing_codes.append(classroom.class_code)
        class_name = request.POST.get('class_name')
        section = request.POST.get('section')
        if request.FILES.get('students_emails'):
            # Get the students' emails from the uploaded csv or xlx file
            students_emails = request.FILES.get('students_emails')
            students_emails = students_emails.read().decode('utf-8').split('\n')
            for email in students_emails:
                email = email.strip()
                if email:
                    # Send an invitation email to the student
                    email.joining_invitation_mail(class_name, email)

        class_code = generate_class_code(6,existing_codes)
        classroom = Classrooms(classroom_name=class_name,section=section,class_code=class_code)
        classroom.save()
        teacher = Teachers(teacher_id=request.user,classroom_id=classroom)
        teacher.save()
        return JsonResponse({'status':'SUCCESS'})

@login_required
def join_class_request(request):
    if request.POST.get('action') == 'post':
        code = request.POST.get('class_code')
        try:
            classroom = Classrooms.objects.get(class_code=code)
            student = Students.objects.filter(student_id = request.user, classroom_id = classroom)
            if (student.count()!=0):
                return redirect('classrooms:home')
        except Exception as e:
            print(e)
            return JsonResponse({'status':'FAIL','message':str(e)})
        student = Students(student_id = request.user, classroom_id = classroom)
        student.save()
        return JsonResponse({'status':'SUCCESS'})



@login_required
def render_class(request,id):
    classroom = Classrooms.objects.get(pk=id)
    try: 
        assignments = Assignments.objects.filter(classroom_id = id)
    except Exception as e:
        assignments = None

    try:
        students = Students.objects.filter(classroom_id = id)
    except Exception as e:
        students = None

    try:
        content = CourseContent.objects.filter(classroom_id = id)
    except Exception as e:
        content = None
    
    teachers = Teachers.objects.filter(classroom_id = id)
    teacher_mapping = Teachers.objects.filter(teacher_id=request.user).select_related('classroom_id')
    student_mapping = Students.objects.filter(student_id=request.user).select_related('classroom_id')
    mappings = chain(teacher_mapping,student_mapping)

    return render(request,'classrooms/class_page.html',{'classroom':classroom,'assignments':assignments,'students':students,'teachers':teachers,"mappings":mappings , 'content':content})

@teacher_required
@login_required
def create_assignment(request,classroom_id):
    teacher_mapping = Teachers.objects.filter(teacher_id=request.user).select_related('classroom_id')
    student_mapping = Students.objects.filter(student_id=request.user).select_related('classroom_id')
    mappings = chain(teacher_mapping,student_mapping)

    if request.method == 'POST':
        form = CreateAssignmentForm(request.POST)
        if form.is_valid():
            assignment_name = form.cleaned_data.get('assignment_name')
            due_date = form.cleaned_data.get('due_date')
            due_time = form.cleaned_data.get('due_time')
            classroom_id = Classrooms.objects.get(pk=classroom_id)
            instructions = form.cleaned_data.get('instructions')
            total_marks = form.cleaned_data.get('total_marks')
            assignment = Assignments(assignment_name = assignment_name,due_date = due_date,due_time=due_time,instructions = instructions,total_marks = total_marks,classroom_id=classroom_id)
            assignment.save()
            email.assignment_post_mail(classroom_id,assignment.id)
            return redirect('classrooms:render_class',id=classroom_id.id)
        else:
            return render(request,'classrooms/create_assignment.html',{'form':form,'mappings':mappings})
    form = CreateAssignmentForm()
    return render(request,'classrooms/create_assignment.html',{'form':form,'mappings':mappings, 'classroom':Classrooms.objects.get(pk=classroom_id)})


@teacher_required
@login_required
def assignment_summary(request,assignment_id):
    assignment = Assignments.objects.filter(pk = assignment_id).first()
    submissions = Submissions.objects.filter(assignment_id = assignment_id)
    teachers = Teachers.objects.filter(classroom_id = assignment.classroom_id)
    teacher_mapping = Teachers.objects.filter(teacher_id=request.user).select_related('classroom_id')
    student_mapping = Students.objects.filter(student_id=request.user).select_related('classroom_id')
    no_of_students = Students.objects.filter(classroom_id=assignment.classroom_id)
    mappings = chain(teacher_mapping,student_mapping)
    return render(request,'classrooms/assignment_summary.html',{'assignment':assignment,'submissions':submissions,'mappings':mappings,'no_of_students':no_of_students})


@teacher_required
@login_required
def delete_assignment(request,assignment_id):
    try:
        assignment = Assignments.objects.get(pk=assignment_id)
        classroom_id = assignment.classroom_id.id 
        Assignments.objects.get(pk=assignment_id).delete()
        return redirect('classrooms:render_class', id=classroom_id)
    except Exception as e:
        return redirect('classrooms:home')

@student_required
@login_required    
def unenroll_class(request,classroom_id):
    classroom = Classrooms.objects.get(pk=classroom_id)
    Students.objects.filter(student_id=request.user,classroom_id=classroom).delete()
    return redirect('classrooms:home')
   

@teacher_required
@login_required
def delete_class(request,classroom_id):
    classroom = Classrooms.objects.get(pk=classroom_id)
    teacher_mapping = Teachers.objects.get(teacher_id=request.user,classroom_id=classroom)
    teacher_mapping.delete()
    classroom.delete()
    return redirect('classrooms:home')


@teacher_required
@login_required
def mark_submission_request(request,submission_id,teacher_id):
    if request.POST.get('action') == 'post':
        marks = request.POST.get('submission_marks')
        submission = Submissions.objects.get(pk=submission_id)
        submission.marks_alloted = marks
        submission.save()
        email.submission_marks_mail(submission_id,teacher_id,marks)
        return JsonResponse({'status':'SUCCESS'})

@student_required
@login_required
def submit_assignment_request(request,assignment_id):
    assignment = Assignments.objects.get(pk=assignment_id)
    student_id = Students.objects.get(classroom_id=assignment.classroom_id,student_id=request.user.id)
    file_name = request.FILES.get('myfile')
    try:
        submission = Submissions.objects.get(assignment_id=assignment, student_id = student_id)
        submission.submission_file = file_name
        submission.save()
        return JsonResponse({'status':'SUCCESS'})

    except Exception as e:  
        print(str(e))  
        submission = Submissions(assignment_id = assignment,student_id= student_id,submission_file = file_name)
        dt1=datetime.now()
        dt2=datetime.combine(assignment.due_date,assignment.due_time)
        time = timesince(dt1, dt2)
        if time[0]=='0':
            submission.submitted_on_time=False
        submission.save()
        email.submission_done_mail(assignment_id,request.user,file_name)
        return JsonResponse({'status':'SUCCESS'})




def generate_class_code(total_digits,existing_codes) :  
    digits = ''.join([str(i) for i in range(0,10)])
    code = ""  
    while True:
        for i in range(total_digits) : 
            code += digits[math.floor(random.random() * 10)] 
        if code not in existing_codes:
            print('Code not in existing codes')
            break
    return code 


@login_required
def add_course(request,classroom_id):
    if request.method == 'POST':
        content_title = request.POST.get('content_title')
        content_description = request.POST.get('content_description')
        content_file = request.FILES.get('content_file')
        if content_file:
            course_content = CourseContent(classroom_id = Classrooms.objects.get(pk=classroom_id),content_title=content_title,content_description=content_description,content_file=content_file)
        else:
            course_content = CourseContent(classroom_id = Classrooms.objects.get(pk=classroom_id),content_title=content_title,content_description=content_description)
        course_content.save()            
    return redirect('classrooms:render_class',id=classroom_id)



@login_required
def dashboard(request):

InTouchLearn/classrooms/templates/classrooms/assignment_summary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'classrooms/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classrooms/css/base_class.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classrooms/css/assignment_summary.css' %}">
    {% block head %}{% endblock %}
    <!-- tailwind -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-purple-100">
      <a class="text-2xl font-bold text-purple-700 hover:no-underline" href="{% url 'classrooms:dashboard' %}">
          <div class="flex">
              <img src="{% static 'socialmedia/images/logo.svg' %}" alt="logo" class="w-10 h-10"> 
              <span class="text-2xl font-bold text-purple-700">Classroom</span>
          </div>
      </a>
      <div class="container mx-auto">
        <div class="text-lg font-semibold"><span>Assignment: </span>{{ assignment.assignment_name }}</div>

  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a href="{% url 'classrooms:render_class' id=assignment.classroom_id.id %}" type="button"  class="m-2 text-lg  nav-link text-purple-700 hover:text-purple-900" >Back to Class</a>
                </li>
                
              </ul>
          </div>
      </div>
  
      <div class="flex items-center">
          <div class="profile-picture">
              <img src="{{ user.profile_picture.url }}" alt="Profile Pic" class="w-10 h-10 rounded-full">
          </div>
      </div>
  </nav>
      
<div class="container">

  <input type="hidden" id="submission_id" name="submission_id">
  <input type="hidden" id="assignment_id" name="assignment_id">
  <input type="hidden" id="user_id" name="user_id">
  <br>
  <h4 class="text-lg font-semibold">
    <span class="mr-4">Total students: {{ no_of_students.count }}</span>
      <span class="mr-4">No. of Submissions: {{ submissions.count }}</span>
      <a href="{% url 'classrooms:delete_assignment' assignment_id=assignment.id %}" class="text-red-500 hover:text-red-700">Delete Assignment</a>
    </h4>
    
    {% for submission in submissions %}
<div class="container_of_submissions mt-8">
    <div class="bg-white rounded-lg shadow-lg p-6">
        <h5 class="text-2xl font-semibold mb-2">student: {{ submission.student_id.student_id.first_name }} {{submission.student_id.student_id.last_name}}</h5>
        <p class="text-gray-600 text-sm mb-2">Submitted at {{ submission.submitted_time }} on {{ submission.submitted_date }}</p>
        <p class="text-gray-600 text-sm mb-2">{{ submission.marks_alloted }} / {{ submission.assignment_id.total_marks }}</p>
        <p class="text-gray-600 text-sm mb-2">Due date and time: {{ submission.assignment_id.due_time }} on {{ submission.assignment_id.due_date }}</p>
        {% if submission.submitted_on_time %}
        <p class="text-gray-600 text-sm mb-2">Submitted on time</p>
        {% else %}
        <p class="text-red-500 text-sm mb-2">Oops! Submitted late</p>
        {% endif %}
        <a href="{{ submission.submission_file.url }}" download class="text-blue-500 hover:text-blue-700 block mb-4">View submitted file</a>
        <a href="#mark_assignment" data-submission_value="{{ submission.id }}" data-assignment_value="{{ submission.assignment_id.id }}" data-user_id="{{ user.id }}" class="text-blue-500 hover:text-blue-700">Mark Submission</a>
    </div>
</div>
{% endfor %}

    
    <div class="modal" tabindex="-1" id="mark_assignment">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Mark Submission</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST" class="cclass_form" id="mark_assignment_form">
              {% csrf_token %}
              <div class="form-group">
                <input type="number" class="form-control" id="submission_marks" placeholder="Submission Marks">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
  
  
  <script>
    $('a[href$="#mark_assignment"]').on( "click", function() {
        $('#mark_assignment').modal('show');
        var assignment_id = $(this).data('assignment_value');
        var submission_id = $(this).data('submission_value');
        var user_id = $(this).data('user_id');

        var assignment_hidden_field = document.getElementById('assignment_id');
        assignment_hidden_field.value = assignment_id;

        var submission_hidden_field = document.getElementById('submission_id');
        submission_hidden_field.value = submission_id;

        var user_hidden_field = document.getElementById('user_id');
        user_hidden_field.value = user_id;

    });

    $('#mark_assignment_form').on('submit', function (e) {
        var submission_id = document.getElementById('submission_id').value;    
        var user_id = document.getElementById('user_id').value;    
        var mark_assignment_url =  "{% url 'classrooms:mark_submission_request' submission_id=1 teacher_id=0 %}".replace('1', submission_id);
        mark_assignment_url = mark_assignment_url.replace('0',user_id)
        console.log(mark_assignment_url);
        var assignment_id = document.getElementById('assignment_id').value;   
        $.ajax({
            type:'POST',
            url:mark_assignment_url,
            data:{
                submission_marks:$('#submission_marks').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json){
                document.getElementById("mark_assignment_form").reset();
                $(".posts").prepend('<div class="col-md-6">'+
                    '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
                        '<div class="col p-4 d-flex flex-column position-static">' +
                            '<h3 class="mb-0">' + json.submission_marks + '</h3>' +
                        '</div>' +
                    '</div>' +
                '</div>' 
                )
                window.location.href='http://127.0.0.1:8000/classrooms/assignment_summary/' + assignment_id.toString();
                window.location.reload();
            },
            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });
      });
</script>
</html> 

InTouchLearn/classrooms/templates/classrooms/parent_class.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{classroom.classroom_name}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'classrooms/css/base_class.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classrooms/css/burger.css' %}">
    <link rel="icon" href="{% static 'socialmedia/images/logo.svg' %}">

    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   
   <style>
    
.navbar1:hover,
.navbar1:active {
  letter-spacing: 5px;
  font-weight: bold;
  color:black ;
}
   </style> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body class="container-fluid">
 
  <nav class="navbar navbar-expand-lg navbar-light bg-purple-100">
    <div class="container mx-auto">

        <a class="text-2xl font-bold text-purple-700 hover:no-underline	" href="{% url 'socialmedia:post-list' %}">
          <div class="flex">
            <img src="{% static 'socialmedia/images/logo.svg' %}" alt="logo" class="w-10 h-10">
            <span class="text-2xl font-bold text-purple-700"> Academy</span>
          </div>
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% for teacher in teachers %}
                    {% if teacher.teacher_id.id == user.id %}
                        <li class="nav-item">
                            <a href="{% url 'classrooms:create_assignment' classroom_id=classroom.id %}" class="nav-link text-purple-700 hover:text-purple-900" style="text-decoration: none;">Create Assignment</a>
                        </li>
                        <li class="nav-item">
                            <a href="#add_course" class="nav-link text-purple-700 hover:text-purple-900" style="text-decoration: none;">Add Course</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'classrooms:delete_class' classroom_id=classroom.id %}" class="nav-link text-purple-700 hover:text-purple-900" style="text-decoration: none;">Delete Class</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="nav-item">
                    <a href="{% url 'classrooms:home' %}" class="nav-link text-purple-700 hover:text-purple-900" style="text-decoration: none;">Home</a>
                </li>
                {% for student in students %}
                    {% if student.student_id.id == user.id %}
                        <li class="nav-item">
                            <a href="{% url 'classrooms:unenroll_class' classroom_id=classroom.id %}" class="nav-link text-purple-700 hover:text-purple-900" style="text-decoration: none;">Unenroll Class</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="flex items-center">
        <div class="profile-picture">
            <img src="{{ user.profile_picture.url }}" alt="Profile Pic" class="w-10 h-10 rounded-full">
        </div>
    </div>
</nav>



      {% block hamburger %}
      {% endblock %}
</body>
<script>
    $('a[href$="#submit_assignment"]').on( "click", function() {
      $('#submit_assignment').modal('show');
      var assignment_id = $(this).data('value');
      var hidden_field = document.getElementById('assignment_id');
      hidden_field.value = assignment_id;
    });

    $('#submit_assignment_form').on('submit', function (e) {
        e.preventDefault();
        var assignment_id = document.getElementById('assignment_id').value;
        var submit_assignment_url =  "{% url 'classrooms:submit_assignment_request' assignment_id=0 %}".replace('0', assignment_id);
        var formData = new FormData(this);
        var class_id = '{{assignment_id.classroom_id.id}}';
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        formData.append('submission_file',$('#myfile'));
        formData.append('csrfmiddlewaretoken', csrftoken);
        $.ajax({
            type:'POST',
            url:submit_assignment_url,
            data:formData,
            cache: false,
            processData: false,
            contentType: false,
            enctype: 'multipart/form-data',
            success:function(json){
                document.getElementById("submit_assignment_form").reset();
                $(".posts").prepend('<div class="col-md-6">'+
                    '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
                        '<div class="col p-4 d-flex flex-column position-static">' +
                        '</div>' +
                    '</div>' +
                '</div>' 
                );
                window.location.href='http://127.0.0.1:8000/class/' + class_id.toString();
                window.location.reload();
            },
            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });
      });

      $('a[href$="#add_course"]').on( "click", function() {
        $('#add_course').modal('show');
      });

      document.addEventListener("DOMContentLoaded", function() {
        // Get the menu toggle checkbox
        var menuToggle = document.getElementById("menuToggle");

        // Get the menu
        var menu = document.getElementById("menu");

        // Add event listener to the checkbox for toggle
        menuToggle.addEventListener("change", function() {
            // If checkbox is checked, show the menu; otherwise, hide it
            if (this.checked) {
                menu.style.display = "block";
            } else {
                menu.style.display = "none";
            }
        });
    });

</script>
</html>